import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, catchError, throwError } from 'rxjs';
import {
  BackendLabReport, LabReport, LabReportStats,
  LabReportFilter, PagedLabReports, LabReportStatus
} from '../models/lab-report.model';

const BASE = 'http://localhost:8081/api';

const AVATAR_COLORS: Array<{ bg: string; color: string }> = [
  { bg: '#EBF3FC', color: '#185FA5' },
  { bg: '#EAF3DE', color: '#3B6D11' },
  { bg: '#FEF3CD', color: '#854F0B' },
  { bg: '#FBEAF0', color: '#993556' },
  { bg: '#F1EFE8', color: '#5F5E5A' },
  { bg: '#E1F5EE', color: '#0F6E56' },
];

@Injectable({ providedIn: 'root' })
export class LabReportService {
  constructor(private http: HttpClient) {}

  getAll(): Observable<BackendLabReport[]> {
    return this.http.get<BackendLabReport[]>(`${BASE}/lab-reports`);
  }

  getById(id: number): Observable<BackendLabReport> {
    return this.http.get<BackendLabReport>(`${BASE}/lab-reports/${id}`);
  }

  create(data: Partial<BackendLabReport>): Observable<BackendLabReport> {
    return this.http.post<BackendLabReport>(`${BASE}/lab-reports`, data).pipe(
      catchError(err => throwError(() => err))
    );
  }

  update(id: number, data: Partial<BackendLabReport>): Observable<BackendLabReport> {
    return this.http.put<BackendLabReport>(`${BASE}/lab-reports/${id}`, data).pipe(
      catchError(err => throwError(() => err))
    );
  }

  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${BASE}/lab-reports/${id}`).pipe(
      catchError(err => throwError(() => err))
    );
  }

  // TODO: backend has no /api/lab-reports/:id/download — generates client-side text blob
  downloadReport(report: LabReport): void {
    const lines = [
      'LAB REPORT — MediConnect',
      '─'.repeat(40),
      `Patient : ${report.patientName} (${report.patientCode})`,
      `Test    : ${report.testName}`,
      `Date    : ${report.reportDate}`,
      `Result  : ${report.resultSummary}`,
      `Status  : ${report.status}`,
      '─'.repeat(40),
      'Generated by MediConnect',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const safeName = `${report.patientName}_${report.testName}_${report.reportDate}`
      .replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_-]/g, '');
    a.href = url;
    a.download = `${safeName}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // Client-side filtering, pagination, and stats
  applyFilter(all: BackendLabReport[], filter: LabReportFilter): PagedLabReports {
    let filtered = [...all];
    const today = this.todayISO();

    if (filter.search) {
      const q = filter.search.toLowerCase();
      filtered = filtered.filter(r => {
        const name = (r.patient?.user?.name || '').toLowerCase();
        const test = (r.testName || '').toLowerCase();
        return name.includes(q) || test.includes(q);
      });
    }

    if (filter.testType) {
      const t = filter.testType.toLowerCase();
      filtered = filtered.filter(r => (r.testName || '').toLowerCase().includes(t));
    }

    if (filter.status) {
      const s = filter.status.toLowerCase();
      filtered = filtered.filter(r => this.normalizeStatus(r.result).toLowerCase() === s);
    }

    if (filter.date) {
      filtered = filtered.filter(r => r.reportDate === filter.date);
    }

    // Sort: most recent first
    filtered.sort((a, b) => (b.reportDate || '').localeCompare(a.reportDate || ''));

    const total = filtered.length;
    const start = (filter.page - 1) * filter.pageSize;
    const page = filtered.slice(start, start + filter.pageSize);

    const stats = this.computeStats(all);

    return {
      data: page.map((r, i) => this.mapToUI(r, start + i)),
      total,
      stats
    };
  }

  mapToUI(r: BackendLabReport, index: number): LabReport {
    const name = r.patient?.user?.name || 'Unknown';
    const initials = name.split(' ').map((n: string) => n[0]).join('').slice(0, 2).toUpperCase() || '??';
    const { bg, color } = AVATAR_COLORS[index % AVATAR_COLORS.length];
    const status = this.normalizeStatus(r.result);
    const resultSummary = this.buildResultSummary(r.result, status);
    return {
      id: String(r.reportId),
      patientId: String(r.patient?.patientId || ''),
      patientName: name,
      patientCode: 'PT-' + String(r.patient?.patientId || 0).padStart(4, '0'),
      patientInitials: initials,
      avatarBg: bg,
      avatarColor: color,
      testName: r.testName || '—',
      reportDate: r.reportDate || '',
      result: r.result || null,
      resultSummary,
      isAbnormal: status === 'Abnormal',
      status,
      raw: r
    };
  }

  private computeStats(all: BackendLabReport[]): LabReportStats {
    const today = this.todayISO();
    const yesterday = this.yesterdayISO();
    const [curY, curM] = today.split('-').map(Number);

    const pending = all.filter(r => this.normalizeStatus(r.result) === 'Pending').length;
    const abnormal = all.filter(r => this.normalizeStatus(r.result) === 'Abnormal').length;

    const thisMonth = all.filter(r => {
      if (!r.reportDate) return false;
      const [y, m] = r.reportDate.split('-').map(Number);
      return y === curY && m === curM;
    }).length;

    const completedToday = all.filter(r =>
      r.reportDate === today && this.normalizeStatus(r.result) !== 'Pending'
    ).length;

    const completedYesterday = all.filter(r =>
      r.reportDate === yesterday && this.normalizeStatus(r.result) !== 'Pending'
    ).length;

    return {
      totalThisMonth: thisMonth,
      pending,
      abnormalFlags: abnormal,
      completedToday,
      completedYesterday
    };
  }

  normalizeStatus(result: string | undefined | null): LabReportStatus {
    const r = (result || '').toUpperCase().trim();
    if (!r || r === 'PENDING') return 'Pending';
    if (r === 'ABNORMAL') return 'Abnormal';
    return 'Ready'; // NORMAL or any other text → Ready
  }

  private buildResultSummary(result: string | undefined | null, status: LabReportStatus): string {
    if (status === 'Pending') return 'Processing…';
    if (!result) return '—';
    const r = result.toUpperCase().trim();
    if (r === 'NORMAL') return 'Normal';
    if (r === 'ABNORMAL') return 'Abnormal result';
    return result; // free-text result
  }

  todayISO(): string {
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  }

  private yesterdayISO(): string {
    const d = new Date();
    d.setDate(d.getDate() - 1);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  }
}
