import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, catchError, throwError } from 'rxjs';
import {
  BackendLabReport, LabReport, LabReportStats,
  LabReportFilter, PagedLabReports, LabReportStatus
} from '../models/lab-report.model';

const BASE = 'http://localhost:8081/api';

const AVATAR_COLORS: Array<{ bg: string; color: string }> = [
  { bg: '#EBF3FC', color: '#185FA5' },
  { bg: '#EAF3DE', color: '#3B6D11' },
  { bg: '#FEF3CD', color: '#854F0B' },
  { bg: '#FBEAF0', color: '#993556' },
  { bg: '#F1EFE8', color: '#5F5E5A' },
  { bg: '#E1F5EE', color: '#0F6E56' },
];

@Injectable({ providedIn: 'root' })
export class LabReportService {
  constructor(private http: HttpClient) {}

  getAll(): Observable<BackendLabReport[]> {
    return this.http.get<BackendLabReport[]>(`${BASE}/lab-reports`);
  }

  getById(id: number): Observable<BackendLabReport> {
    return this.http.get<BackendLabReport>(`${BASE}/lab-reports/${id}`);
  }

  create(data: Partial<BackendLabReport>): Observable<BackendLabReport> {
    return this.http.post<BackendLabReport>(`${BASE}/lab-reports`, data).pipe(
      catchError(err => throwError(() => err))
    );
  }

  update(id: number, data: Partial<BackendLabReport>): Observable<BackendLabReport> {
    return this.http.put<BackendLabReport>(`${BASE}/lab-reports/${id}`, data).pipe(
      catchError(err => throwError(() => err))
    );
  }

  delete(id: number): Observable<void> {
    return this.http.delete<void>(`${BASE}/lab-reports/${id}`).pipe(
      catchError(err => throwError(() => err))
    );
  }

  downloadReport(report: LabReport): void {
    const statusColor = report.status === 'Abnormal' ? '#B91C1C' : report.status === 'Ready' ? '#0F7B50' : '#B45309';
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Lab Report - ${report.testName}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #1a1a2e; }
  .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #185FA5; padding-bottom: 16px; margin-bottom: 24px; }
  .logo { font-size: 22px; font-weight: 700; color: #185FA5; }
  .logo span { color: #1D9E75; }
  .title { font-size: 18px; font-weight: 700; color: #0D2B4E; margin-bottom: 20px; }
  .row { display: flex; gap: 40px; margin-bottom: 16px; }
  .field { flex: 1; }
  .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #8A94A6; margin-bottom: 4px; }
  .value { font-size: 14px; color: #0D2B4E; font-weight: 500; }
  .status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; background: ${statusColor}18; color: ${statusColor}; }
  .result-box { background: #F2F4F8; border-radius: 8px; padding: 16px; margin: 20px 0; border-left: 4px solid ${statusColor}; }
  .result-box .label { margin-bottom: 8px; }
  .result-text { font-size: 15px; color: #0D2B4E; font-weight: 500; white-space: pre-wrap; }
  .footer { border-top: 1px solid #E5E7EB; margin-top: 40px; padding-top: 16px; font-size: 11px; color: #8A94A6; display: flex; justify-content: space-between; }
  @media print { body { margin: 20px; } }
</style></head><body>
<div class="header"><div class="logo">Medi<span>Connect</span></div><div style="font-size:12px;color:#8A94A6">Lab Report</div></div>
<div class="title">Laboratory Report</div>
<div class="row">
  <div class="field"><div class="label">Patient Name</div><div class="value">${report.patientName}</div></div>
  <div class="field"><div class="label">Patient ID</div><div class="value">${report.patientCode}</div></div>
</div>
<div class="row">
  <div class="field"><div class="label">Test Name</div><div class="value">${report.testName}</div></div>
  <div class="field"><div class="label">Report Date</div><div class="value">${report.reportDate}</div></div>
  <div class="field"><div class="label">Status</div><div class="value"><span class="status-badge">${report.status}</span></div></div>
</div>
<div class="result-box">
  <div class="label">Result</div>
  <div class="result-text">${report.resultSummary || report.result || '—'}</div>
</div>
<div class="footer"><span>Generated by MediConnect HMS</span><span>${new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' })}</span></div>
<script>window.onload = function(){ window.print(); }<\/script>
</body></html>`;
    const w = window.open('', '_blank');
    if (w) { w.document.write(html); w.document.close(); }
  }

  // Client-side filtering, pagination, and stats
  applyFilter(all: BackendLabReport[], filter: LabReportFilter): PagedLabReports {
    let filtered = [...all];
    const today = this.todayISO();

    if (filter.search) {
      const q = filter.search.toLowerCase();
      filtered = filtered.filter(r => {
        const name = (r.patient?.user?.name || '').toLowerCase();
        const test = (r.testName || '').toLowerCase();
        return name.includes(q) || test.includes(q);
      });
    }

    if (filter.testType) {
      const t = filter.testType.toLowerCase();
      filtered = filtered.filter(r => (r.testName || '').toLowerCase().includes(t));
    }

    if (filter.status) {
      const s = filter.status.toLowerCase();
      filtered = filtered.filter(r => this.normalizeStatus(r.result).toLowerCase() === s);
    }

    if (filter.date) {
      filtered = filtered.filter(r => r.reportDate === filter.date);
    }

    // Sort: most recent first
    filtered.sort((a, b) => (b.reportDate || '').localeCompare(a.reportDate || ''));

    const total = filtered.length;
    const start = (filter.page - 1) * filter.pageSize;
    const page = filtered.slice(start, start + filter.pageSize);

    const stats = this.computeStats(all);

    return {
      data: page.map((r, i) => this.mapToUI(r, start + i)),
      total,
      stats
    };
  }

  mapToUI(r: BackendLabReport, index: number): LabReport {
    const name = r.patient?.user?.name || 'Unknown';
    const initials = name.split(' ').map((n: string) => n[0]).join('').slice(0, 2).toUpperCase() || '??';
    const { bg, color } = AVATAR_COLORS[index % AVATAR_COLORS.length];
    const status = this.normalizeStatus(r.result);
    const resultSummary = this.buildResultSummary(r.result, status);
    return {
      id: String(r.reportId),
      patientId: String(r.patient?.patientId || ''),
      patientName: name,
      patientCode: 'PT-' + String(r.patient?.patientId || 0).padStart(4, '0'),
      patientInitials: initials,
      avatarBg: bg,
      avatarColor: color,
      testName: r.testName || '—',
      reportDate: r.reportDate || '',
      result: r.result || null,
      resultSummary,
      isAbnormal: r.isAbnormal ?? (status === 'Abnormal'),
      status,
      raw: r
    };
  }

  private computeStats(all: BackendLabReport[]): LabReportStats {
    const today = this.todayISO();
    const yesterday = this.yesterdayISO();
    const [curY, curM] = today.split('-').map(Number);

    const pending = all.filter(r => this.normalizeStatus(r.result) === 'Pending').length;
    const abnormal = all.filter(r => r.isAbnormal === true || this.normalizeStatus(r.result) === 'Abnormal').length;

    const thisMonth = all.filter(r => {
      if (!r.reportDate) return false;
      const [y, m] = r.reportDate.split('-').map(Number);
      return y === curY && m === curM;
    }).length;

    const completedToday = all.filter(r =>
      r.reportDate === today && this.normalizeStatus(r.result) !== 'Pending'
    ).length;

    const completedYesterday = all.filter(r =>
      r.reportDate === yesterday && this.normalizeStatus(r.result) !== 'Pending'
    ).length;

    return {
      totalThisMonth: thisMonth,
      pending,
      abnormalFlags: abnormal,
      completedToday,
      completedYesterday
    };
  }

  normalizeStatus(result: string | undefined | null): LabReportStatus {
    const r = (result || '').toUpperCase().trim();
    if (!r || r === 'PENDING') return 'Pending';
    if (r === 'ABNORMAL') return 'Abnormal';
    return 'Ready'; // NORMAL or any other text → Ready
  }

  private buildResultSummary(result: string | undefined | null, status: LabReportStatus): string {
    if (status === 'Pending') return 'Processing…';
    if (!result) return '—';
    const r = result.toUpperCase().trim();
    if (r === 'NORMAL') return 'Normal';
    if (r === 'ABNORMAL') return 'Abnormal result';
    return result; // free-text result
  }

  todayISO(): string {
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  }

  private yesterdayISO(): string {
    const d = new Date();
    d.setDate(d.getDate() - 1);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
  }
}
